### ISSUE TITLE
Easing/Transitioning in Chrome

### ISSUE THREAD

**Issue by skipjack** [d3/d3-ease#16]
> I think this issue should probably be moved elsewhere, I'm just not really sure where else to put it yet. I'm more just trying to gather thoughts than anything else as I feel like other d3 users must have ran into this issue as well...

I have some code that translates a `g` element via `d3-transition` and `d3-ease`:

``` js
d3.select(this.container)
    .transition()
    .duration(1200)
    .ease(Easing)
    .attrTween('transform', () => {
        var i = Interpolate(0, 360)

        return function(t) {
            return `translate(105, 107.5) rotate(${i(t)})`
        })
    })
    .on('end', (d, i) => {
        if (this.props.loading) this._rotate() // Recalls this function
           else this._slideIn() // Ends the animation
    })
```

This code works flawlessly in Firefox and used to in Chrome as well, however after a recent Chrome update within the last year or so the transition started to look very odd. By this I mean instead of rotating 360 degrees and bouncing upon completion, it does this back and forth rocking while slowly orbiting around.

When I inspect the DOM, I see the `rotate()` values within the `transform` attribute being modified properly. Even slowing the animation doesn't help and, in fact, I've seen some other odd behaviors (such as rewinding when moving from 360 => 0) while trying to debug.

Again, I think this is probably not an issue with this repo or d3 in general and I'm happy to move elsewhere that would make more sense.

**Comment by mbostock** [comment]
If you can post an example on bl.ocks.org or similar so I can take a look, that’d be great. If you can’t, unfortunately I can’t think of an immediate reason why the code above wouldn’t work as expected… sorry.

**Comment by skipjack** [comment]
Yep here's [a pen](https://codepen.io/gvenech/pen/38dbfd737ea64b3a98c69f4bfb378d6d?editors=0010) that has the issue. That example is using v3 but it's essentially the same issue. It would take me a few days as I don't have time right this but I can update pen that to v4 if it'd be helpful.

Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/8988697/29999481-b7ffb40c-9018-11e7-816b-e267b5d0a425.png)

May be a little tough to see in the gif, but it essentially just jerks back and forth erratically during the rotation.

You should be able to see the issue in Chrome (v60.0.3112.101 in my case), but if you open in another browser (Firefox is the other I tested) the animation runs perfectly. Thanks for your help!

**Comment by mbostock** [comment]
Thanks, that identified the problem. It’s your style here:

```css
#q-loader * {
  transition: all 500ms;
}
```

When you do that, *any* change you make to a style on any descendent of #q-loader has a 500ms transition. In modern browsers, [SVG presentation attributes](https://www.w3.org/TR/SVG/styling.html#UsingPresentationAttributes) have been unified with styles, so this style rule also applies to the transform attribute you are setting through JavaScript. Each time JavaScript changes the transform attribute, it triggers a new CSS transition, so the JavaScript doesn’t have a chance to run.

Either you should disable (or reduce the scope) or your transition CSS style, or you should not just JavaScript to run the transition.

**Comment by skipjack** [comment]
Ah I see, that makes sense. Didn't realize `transition` would affect `transform` attribute. Thanks for your help!
