### ISSUE TITLE
README references obsolete APIs.

### ISSUE THREAD

**Issue by tmcw** [d3/d3-ease#20]
Right now several methods that use `.exponent()` have demo images that document their usage with a second argument specifying the exponent as an argument.

![image](https://user-images.githubusercontent.com/32314/59541837-fad60480-8eb7-11e9-9b6d-de07dcadc57d.png)

I think this refers to an older API of this module, and we'll need to update the images.

**Comment by mbostock** [comment]
Yes, we should migrate this documentation to Observable so it’s easier to update.

**Comment by Fil** [comment]
This [notebook](https://observablehq.com/d/a1146016662ae4f3) generates all the images.

**Comment by Fil** [comment]
with the new github page design the images are enlarged to *ugly*. A solution is to remove the size hints in the `img` tags (currently `width=100% height=240`).
